[env:lilygo-t-display-s3]
platform = espressif32 @ 6.5.0
board = lilygo-t-display-s3
framework = arduino

upload_port = /dev/cu.usbmodem3101
monitor_speed = 115200

build_flags =
    -DUSER_SETUP_LOADED
    -include include/display_setup.h
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bodmer/TFT_eSPI @ 2.5.43
    bblanchon/ArduinoJson @ 7.4.2
board_build.filesystem = littlefs
